name: tarcking_app
description: "Tracking app for flower application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.14
  another_flushbar: ^1.12.32
  get: ^4.7.2
  get_it: ^8.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.1
  intl: any
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  logger: ^2.6.1
  path_provider: ^2.1.5
  retrofit: ^4.1.0
  smooth_page_indicator: ^1.2.1
  country_flags: ^4.0.1
  file_picker: ^8.1.2
  shared_preferences: ^2.5.3
  mockito:
  image_picker: ^1.2.0
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.3.2
  firebase_messaging: ^16.0.2
  location:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http:

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  flutter_lints: ^5.0.0
  remove_from_coverage: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf